// ========== 站点数据 ==========
const SITES = {
    direct: [
        { name: "触摸gal", url: "https://www.touchgal.com/" },
        { name: "下雪阁", url: "https://xiayuge.top/" },
        { name: "西林辞苑", url: "https://www.xilinciyua.cc/" },
        { name: "心酷动漫", url: "https://www.shinnku.com/" },
        { name: "恋站ACG", url: "https://lzacg.org/" },
        { name: "亭亭立", url: "https://www.ttloli.com/" },
        { name: "樱花之星", url: "https://sakustar.moe/" },
        { name: "ACG资源站", url: "https://www.acgnzy.com/" },
        { name: "酒井里奥", url: "https://sakakirio.com/" },
        { name: "萝莉ACG", url: "https://loliacg.xyz/" },
        { name: "Galzy", url: "https://galzy.eu.org/" },
        { name: "2dfan下载", url: "https://2dfan.org/downloads/" },
        { name: "CNGAL", url: "https://www.cngal.org/" },
        { name: "ACG资源网", url: "https://acgyw.xyz/category/game/" },
        { name: "VikACG", url: "https://www.vikacg.com/post" },
        { name: "画廊PW", url: "https://gallibrary.pw/" },
        { name: "ACG云馆", url: "https://acgyyg.ru/" },
        { name: "ACG知道", url: "https://acgknow.me/" },
        { name: "壹叁叁", url: "https://1ov3.top/" },
        { name: "GalSaop", url: "https://gal.saop.cc/" },
        { name: "樱雨Gal", url: "https://yinghu.netlify.app/" },
        { name: "子零", url: "https://zi0.cc/" },
        { name: "昆伽", url: "https://www.kungal.com/zh-cn" },
        { name: "WafuWafu", url: "https://wafuwafu.com/" },
        { name: "GalXP", url: "https://www.galxp.com/" },
        { name: "Kdays论坛", url: "https://bbs2.kdays.net/" },
        { name: "ACGGW", url: "https://www.acggw.club/" },
        { name: "KFpromax", url: "https://kfpromax.com/index.php" },
        { name: "甜Gal", url: "https://www.tiangal.com/" },
        { name: "空ACG", url: "https://www.soraacg.com/" },
        { name: "零零ACG", url: "https://llssacg.live/" },
        { name: "ACG趣", url: "https://acgfun.moe/" },
        { name: "芙芙Gal", url: "https://fufugal.com/" },
        { name: "ACGN社区", url: "https://www.acgnsq.com/" },
        { name: "BBFTT", url: "https://bbftt.github.io/" },
        { name: "木图ACG", url: "https://www.mtuacg.cc/portal.php" },
        { name: "老王2222", url: "https://www.laowang2222.com/" },
        { name: "爱色影", url: "https://www.aisecy.com/" },
        { name: "FunForACG", url: "https://funforacg.github.io/" },
        { name: "Lzone", url: "https://lzone.moe/Home/About" },
        { name: "GogalGame", url: "https://www.gogalgame.com/" },
        { name: "GTACGG", url: "https://gtacgg.com/" },
        { name: "FHXY", url: "https://fh-xy.net/" },
        { name: "DMO LOL", url: "https://dmo.lol/" },
        { name: "2cyshare", url: "https://www.2cyshare.com/" },
        { name: "Upacg", url: "https://www.upacg.cc/" },
        { name: "Xhcyra", url: "https://xhcyra.com/" },
        { name: "YZWY", url: "https://www.yzwy.cc/" },
        { name: "YX ACGCYLY", url: "https://yx.acgcyly.com/yxzy/rxyx" },
        { name: "Wuaiacg", url: "https://www.wuaiacg1.com/" },
        { name: "05fx", url: "https://05fx.022016.xyz/" },
        { name: "Zyxz Ailoli", url: "https://zyxz.ailoli.us/" },
        { name: "Sayafx", url: "https://www.sayafx.top/" },
        { name: "Bzhai", url: "https://www.bzhai.com/game.html" },
        { name: "Galcg", url: "https://www.galcg.org/" },
        { name: "Seikuu", url: "https://bbs2.seikuu.com/" },
        { name: "Sumisora", url: "https://bbs.sumisora.net/index.php" },
        { name: "Hikarinagi", url: "https://www.hikarinagi.com/" },
        { name: "66gal", url: "https://www.66gal.com/" },
        { name: "Yuanzkong", url: "https://yuanzkong.github.io/" },
        { name: "Bakadax", url: "https://file.bakadax.top/" },
        { name: "Ille13", url: "https://www.ille13.com/" },
        { name: "Newyx", url: "https://m.newyx.net/heji/galgame/" },
        { name: "ACGNDOG", url: "https://www.acgndog.com/category/game/lvg" },
        { name: "Pan CYCyg", url: "https://pan.cycg.xyz/" },
        { name: "Pan Cangshui", url: "https://pan.cangshui.net/" },
        { name: "Portbox", url: "https://portbox.lol/" },
        { name: "7dmao", url: "https://www.7dmao.com/zhuti/46/1.html" },
        { name: "114514", url: "https://114514.1919180.xyz/" },
        { name: "Nekogal", url: "https://www.nekogal.com/" },
        { name: "Letaoke", url: "https://www.letaoke.cn/" },
        { name: "Xbgame", url: "https://www.xbgame.net/" },
        { name: "2cycdx", url: "https://www.2cycdx.com/forum.php?mod=forumdisplay&fid=42&mobile=2" },
        { name: "Cyzd", url: "https://www.cyzd.me" },
        { name: "Acg880", url: "https://www.acg880.com/" },
        { name: "Acgdh", url: "https://www.acgdh.cc/" },
        { name: "Nav Acgsq", url: "https://nav.acgsq.com/acgdh" },
        { name: "Acgdhwz", url: "https://acgdhwz.com/" },
        { name: "Acgfans", url: "https://www.acgfans.me/" },
        { name: "Extnav", url: "https://www.extnav.cn/acgn" },
        { name: "Mengzhan65", url: "https://vxw2.mengzhan65.top/index.php" },
        { name: "Coklw", url: "https://coklw.xyz/archives/category/yx" },
        { name: "Hggard", url: "https://hggard.com/Blog/List/4" },
        { name: "Otomedream", url: "https://www.otomedream.com/forum.php?mod=forumdisplay&fid=35852&mobile=2" },
        { name: "Erogames", url: "https://erogames.com/" },
        { name: "Freegogpcgames", url: "https://freegogpcgames.com/visual-novel/" },
        { name: "Kimochi", url: "https://kimochi.info/" },
        { name: "Acgmes", url: "https://www.acgmes.com/" },
        { name: "Hentai-sharing", url: "https://hentai-sharing.net/" },
        { name: "Hahajingzi", url: "https://hahajingzi.github.io/" },
        { name: "Ryuugames", url: "https://www.ryuugames.com/" },
        { name: "R18zgqinc", url: "https://r18zgqinc.wordpress.com/" },
        { name: "Acgbk", url: "https://acgbk.top/" },
        { name: "Gacg", url: "https://www.gacg.pro/" },
        { name: "Acgns", url: "https://www.acgns.org/" },
        { name: "Slgjoy", url: "https://www.slgjoy.top/category/youxi/" }
    ],
    proxy: [
        { name: "Freem", url: "https://www.freem.ne.jp/" },
        { name: "Mwmoe", url: "https://mwmoe.lol/" },
        { name: "MSK眼科", url: "https://www.msk-eyelasik.cn/" }
    ],
    dead: [
        { name: "Galgame.ink", url: "https://www.galgame.ink/" },
        { name: "Moyegalga", url: "https://moyegalga.me/tag/krkr/" },
        { name: "轻语ACG", url: "https://post.qingjuacg.org/" },
        { name: "IACG世界", url: "https://iacg.world/" },
        { name: "Galgameacgjohn", url: "https://www.galgameacgjohn.top/" },
        { name: "Pan jlbx", url: "https://pan.jlbx.xyz/" }
    ]
};
